#!/bin/bash
# Increments the build counter and regenerates the build-info header.
# Run by the Makefile whenever a tracked source file changes.
set -e

OUT="$1"
COUNTER="$(dirname "$0")/../.build-number"

number=$(cat "$COUNTER" 2>/dev/null || echo 0)
number=$((number + 1))
echo "$number" > "$COUNTER"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<HEADER
#pragma once

/** Generated by tools/bump-build.sh. Bumps whenever a source file changes, so the number
printed on the panel says which build Rack has loaded. */
#define M32_BUILD_NUMBER $number
#define M32_BUILD_TIME "$(date '+%Y-%m-%d %H:%M:%S')"
HEADER

echo "==> M32 build $number"
